### ISSUE TITLE
Incomplete supported languages list

### ISSUE THREAD

**Issue by tuttitut** [Language-Tools/anki-vocabai#5]
DeepL supports English to Norwegian translations, but the baserow sheet does not allow this combination. DeepL is the only high-quality translator for Norwegian, so I won't be using this addon yet. Hope this will be fixed in the future!

**Comment by luc-vocab** [comment]
OK I can add norwegian, please give me a bit of time to add this.

**Comment by luc-vocab** [comment]
moved to https://github.com/Vocab-Apps/baserow-vocabai-plugin/issues/11
